[package]
name = "daw-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
daw-bridge = { path = "../daw-bridge" }
gpui = "0.2.2"
itertools = "0.12"
libc = "0.2"
memmap2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
